# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-11 17:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import core.models.helpers


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to=core.models.helpers.image_path)),
                ('address', models.CharField(max_length=255, verbose_name='Адреса')),
                ('sex', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1, verbose_name='Стать')),
                ('phone', models.CharField(blank=True, max_length=12, verbose_name='Номер телефону')),
                (
                'user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профіль користувача',
                'verbose_name_plural': 'Профілі користувачів',
                'ordering': ('-id',),
            },
        ),
    ]
