# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_profile', '0002_auto_20180111_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, verbose_name="Введіть ім'я")),
                ('lastname', models.CharField(max_length=40, verbose_name='Введіть прізвище')),
                ('surename', models.CharField(max_length=20, verbose_name='Введіть по-батькові')),
                ('dob', models.DateField(max_length=4, verbose_name='вік дитини')),
                ('sex', models.CharField(choices=[('F', 'female'), ('M', 'male')], max_length=1, verbose_name='Стать')),
                ('parents', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Профілі користувачів',
                'verbose_name': 'Профіль користувача',
            },
        ),
    ]
