# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 09:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0003_child'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='child',
            old_name='surename',
            new_name='sure_name',
        ),
        migrations.AlterField(
            model_name='child',
            name='parents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile',
                                       to=settings.AUTH_USER_MODEL),
        ),
    ]
