# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0004_auto_20180130_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='privilege',
            field=models.PositiveIntegerField(choices=[(0, '---'), (1, 'Інваліди I-шої групи'), (
            1, 'Діти-інваліди, які не мають протипоказань до відвідування ДНЗ'), (1,
                                                                                  'Діти Військовослужбовців Збройних сил України, Національної гвардії учасників АТО'),
                                                       (1,
                                                        'Учасник ліквідації наслідків катастрофи на Чорнобильській АЕС, потерпілих від екологічного та іншого             стихійного лиха, аварій, катастроф'),
                                                       (1, 'Діти під опікою')], default=0,
                                              verbose_name='Тип пільги дитини'),
        ),
    ]
