# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-17 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('user_profile', '0005_child_privilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.City'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='flat',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Номер квартири'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='house',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Будинок'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='house_symbol',
            field=models.CharField(blank=True, max_length=2, verbose_name='Символ будинку'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(default=None, max_length=100, null=True, verbose_name='Вулиця'),
        ),
    ]
