# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_child_privilege'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Дитина', 'verbose_name_plural': 'Діти'},
        ),
    ]
