# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-08 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('user_profile', '0005_child_privilege'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Профіль дитини', 'verbose_name_plural': 'Профілі дітей'},
        ),
        migrations.RenameField(
            model_name='child',
            old_name='sure_name',
            new_name='surname',
        ),
        migrations.AddField(
            model_name='child',
            name='birth_sertificate',
            field=models.CharField(default='', max_length=255, verbose_name='Дані документу'),
        ),
        migrations.AddField(
            model_name='child',
            name='birth_sertificate_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер свідотства'),
        ),
        migrations.AddField(
            model_name='child',
            name='birth_sertificate_series',
            field=models.CharField(default='', max_length=100, verbose_name='Серія свідотства про народження'),
        ),
        migrations.AddField(
            model_name='child',
            name='city',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='location.City'),
        ),
        migrations.AddField(
            model_name='child',
            name='flat',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер квартири'),
        ),
        migrations.AddField(
            model_name='child',
            name='house',
            field=models.PositiveIntegerField(default=0, verbose_name='Будинок'),
        ),
        migrations.AddField(
            model_name='child',
            name='privilege_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер документа'),
        ),
        migrations.AddField(
            model_name='child',
            name='privilege_series',
            field=models.CharField(default='', max_length=100, verbose_name='Серія документа'),
        ),
        migrations.AddField(
            model_name='child',
            name='street',
            field=models.CharField(default='', max_length=100, verbose_name='Вулиця'),
        ),
    ]
