# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_auto_20180221_1246'),
        ('user_profile', '0006_auto_20180213_1855'),
        ('user_profile', '0006_auto_20180217_0736'),
    ]

    operations = [
    ]
