# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-01 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_merge_20180301_1800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'verbose_name': 'Дитина', 'verbose_name_plural': 'Діти'},
        ),
        migrations.AlterField(
            model_name='child',
            name='privilege_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Номер документа'),
        ),
        migrations.AlterField(
            model_name='child',
            name='privilege_series',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Серія документа'),
        ),
    ]
