# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-18 14:12
from __future__ import unicode_literals

import core.models.helpers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to=core.models.helpers.image_path)),
                ('disctict', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('advantages', models.TextField()),
                ('groups', models.ManyToManyField(to='kindergarten.Group')),
            ],
        ),
    ]
