# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('kindergarten', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kindergarten',
            old_name='disctict',
            new_name='district',
        ),
    ]
