# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='group',
        ),
        migrations.AddField(
            model_name='kindergarden',
            name='groups',
            field=models.ManyToManyField(to='kindergarten.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=250),
        ),
    ]
