# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-30 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0002_auto_20180130_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergarten',
            name='address',
            field=models.CharField(default='', max_length=40, verbose_name='номер будинку'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindergarten', to='location.District'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='street',
            field=models.CharField(default='', max_length=40, verbose_name='Вулиця'),
        ),
    ]
