# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 17:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('kindergarten', '0002_auto_20180130_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='kindergarten',
            name='address',
            field=models.CharField(default='', max_length=40, verbose_name='номер будинку'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kindergarten', to='location.District'),
        ),
        migrations.AlterField(
            model_name='kindergarten',
            name='street',
            field=models.CharField(default='', max_length=40, verbose_name='Вулиця'),
        ),
    ]
