# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-06 18:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0005_child_privilege'),
        ('kindergarten', '0003_auto_20180206_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=35)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QueueChildRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('status',
                 models.CharField(choices=[('A', 'Прийнята'), ('W', 'На розгляді'), ('D', 'Відмовлено')], max_length=2,
                                  verbose_name='Статус дитини в черзі')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_profile.Child')),
                ('queue',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.Queue', unique=True)),
            ],
            options={
                'ordering': ('-child__privilege', 'created'),
            },
        ),
        migrations.AddField(
            model_name='queue',
            name='children',
            field=models.ManyToManyField(related_name='queues', through='kindergarten.QueueChildRelation',
                                         to='user_profile.Child'),
        ),
        migrations.AddField(
            model_name='queue',
            name='kindergarten',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queue',
                                    to='kindergarten.Kindergarten'),
        ),
        migrations.AlterUniqueTogether(
            name='queuechildrelation',
            unique_together=set([('child', 'queue')]),
        ),
    ]
