# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-11 11:28
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('kindergarten', '0004_auto_20180206_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuechildrelation',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kindergarten.Queue'),
        ),
    ]
