# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-21 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kindergarten', '0005_auto_20180211_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuechildrelation',
            name='status',
            field=models.CharField(choices=[('A', 'Прийнята'), ('W', 'На розгляді'), ('D', 'Відмовлено')], default='W', max_length=2, verbose_name='Статус дитини в черзі'),
        ),
    ]
